### ISSUE TITLE
Can't connect to tuneblade

### ISSUE THREAD

**Issue by doodieb15** [richmansfield/homebridge-tuneblade#1]
I'm running IOS10.3 and the homebridge on an Raspberry. I've created plugins as well and wanted to use the Tuneblade plugin.

However the plugin can't connect to tuneblade, it runs into a timeout. It can neither get the Status nor set the Status of tuneblade. It can neither set the volume nor get it.

Any ideas how to troubleshoot? When opening the IP Adress with port and devices, I can see the data of tuneblade.

**Comment by richmansfield** [comment]
Hi,

The latest update of Tuneblade seems to have changed the API behaviour, the PUT call no longer sends any return value which means the request objects never get to the callback. 

I have a fix for this, but am away from home on business today so will check in tomorrow.

Rich

**Comment by richmansfield** [comment]
I have just managed to update .js file - could you try again with the latest version here in GitHub, and if this works I will update npm too?

**Comment by doodieb15** [comment]
Tested and yes it's working, Thanks for your fast repsonse!
